jobs:
  - script: >
      multibranchPipelineJob('configuration-as-code2') {
          branchSources {
              git {
                  id = 'configuration-as-code2'
                  remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
              }
          }
      }